# Generated by Django 6.0.1 on 2026-01-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='통화 코드')),
                ('name', models.CharField(max_length=50, verbose_name='통화명')),
                ('base_rate', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='매매기준율')),
                ('cash_buy_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='현찰 살 때')),
                ('cash_sell_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='현찰 팔 때')),
                ('remit_send_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='송금 보낼 때')),
                ('remit_receive_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='송금 받을 때')),
                ('date', models.DateField(db_index=True, verbose_name='고시일')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='수집 시간')),
            ],
            options={
                'verbose_name': '환율',
                'verbose_name_plural': '환율 목록',
                'ordering': ['-date', 'code'],
                'indexes': [models.Index(fields=['code', 'date'], name='exchange_ra_code_9ad67a_idx')],
                'unique_together': {('code', 'date')},
            },
        ),
    ]
